language: objective-c
xcode_workspace: Carpaccio.xcworkspace
xcode_scheme: Carpaccio-iOS
osx_image: xcode8
script: 

stages:
  - build
  - test_ios

build_project:
  stage: build
  script:
    - ssh-keyscan github.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
    - git submodule sync
    - git submodule update --init --recursive
    - carthage bootstrap --use-ssh --use-submodules --platform mac
    - xcodebuild -workspace Carpaccio.xcworkspace -scheme Carpaccio-OSX clean build
  tags:
    - xcode-8.2
    - macos-10.11

test_ios:
  stage: test_ios
  script:
    - xcodebuild -sdk iphonesimulator -workspace Carpaccio.xcworkspace -scheme Carpaccio-iOS -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' clean test | xcpretty
  dependencies:
    - build_project
  tags:
    - xcode-8.2
    - macos-10.11