stages:
  - build_macos
  - build_ios
  - test_ios
  - test_macos

build_macos:
  stage: build_macos
  script:
    - xcodebuild -workspace Carpaccio.xcworkspace -scheme Carpaccio-OSX clean build
  tags:
    - xcode-8.3
    - macos-10.12

build_ios:
  stage: build_ios
  script:
   - xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.3' -workspace Carpaccio.xcworkspace -scheme Carpaccio-iOS clean build | xcpretty

test_macos:
  stage: test_macos
  script:
   - xcodebuild -workspace Carpaccio.xcworkspace -scheme Carpaccio-OSX clean test | xcpretty
  dependencies:
    - build_macos
  tags:
    - xcode-8.3
    - macos-10.12

test_ios:
  stage: test_ios
  script:
    - xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.2' -workspace Carpaccio.xcworkspace -scheme Carpaccio-iOS clean test | xcpretty
  dependencies:
    - build_ios
  tags:
    - xcode-8.3
    - macos-10.12
